spring:
  application:
    name: hivemq-broker
  mvc:
    async:
      request-timeout: 0


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25432/mqtt-broker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    # password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
mqtt:
  brokers:
    default:
      userName: ${MQTT_USERNAME:}
      password: ${MQTT_PASSWORD:}
    "2":
      userName: ${MQTT_BROKER_CLOUD1_USERNAME:}
      password: ${MQTT_BROKER_CLOUD1_PASSWORD:}
  publisher:
    qos: 1
    retain: true
  consumer:
    batch-size: 10
    batch-timeout-ms: 8000

